# Generated by Django 3.2.5 on 2021-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_eCommerce', '0003_alter_product_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='', max_length=100),
        ),
    ]
