# Generated by Django 3.2.5 on 2021-07-16 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite_eCommerce', '0004_product_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addressline1', models.CharField(max_length=300)),
                ('Addressline2', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=90)),
                ('Zipcode', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('alter_mobile', models.CharField(blank=True, max_length=10)),
                ('address', models.ManyToManyField(to='mysite_eCommerce.ShippingAddress')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
